ctrl+Dの挙動を修正
ToYeah/42_minishell pull request #106
Opened 2021-03-13 15:56 UTC by nafuka11

## やったこと
入力中 ctrl+D を押した時、入力した文字を破棄してしまう問題を修正しました！

1. `loop_shell()` ： `buf_line` を追加
   `loop_shell()` に `buf_line` を追加し、ctrl+Dが押された時 `buf_line` に 入力文字列 `line` が join されていくようになっています。
   コマンド実行時、 line ではなく `buf_line` を実行するようにしました。

2. global変数 `g_interrupted` 追加
   SIGINT を受け取ると `buf_line` が残ったままになってしまうため、global変数 `g_interrupted` をフラグとして追加して、SIGINTを受け取ったかTRUE/FALSEでわかるようにしました。
   SIGINT を受け取ったら、ハンドラでTRUEにし、`process_input` でTRUEだったら `buf_line` をfreeします。

3. リファクタリング
   関数が長くなったため、 `handle_eof` にEOFの処理を切り出しました。

4. Makefileの微修正
    leaks を .PHONYに入れ忘れていたので入れました。

## テスト
https://github.com/ToYeah/42_minishell/issues/61#issuecomment-791260783 の Ctrl+Dのケースを実施し全てOK。

追加で以下のケースを実施。全てOK。

No | 条件 | 入力 | 出力 | 終了ステータス
-- | -- | -- | -- | --
19 | ls | Ctrl + D -> Ctrl + C | bash-3.2$ ls<br>bash-3.2$ | 1
20 | aaaaa<Ctrl + D>bbbb<Ctrl + D>\<Enter> | <>の箇所入力 | bash-3.2$ aaaaabbbb<br>bash: aaaaabbbb: command not found | 127
21 | echo <Ctrl + D>hello\<Enter> | <>の箇所入力 | bash-3.2$ echo hello<br>hello | 0
22 | echo hello<Ctrl + D><Ctrl + \\>\<Enter> | <>の箇所入力 | bash-3.2$ echo hello<br>hello | 0
23 | <1023文字分入力><Ctrl + D><任意の文字入力>\<Enter> | <>の箇所入力 | 1-24文字を超えて文字入力できること、Enterで入力文字が反映されていることを確認 | - |
24 | ls<Ctrl + D><Ctrl + D> | <>の箇所入力 | Ctrl + D 入力後、コマンドが実行されないことを確認 | - |

## 気になっていること
global変数が多すぎるので、構造体 t_shell を作って、そこに既存のglobal変数を入れ、 g_shell で持たせた方がいいのかなと思ってます。
`g_interrupted` と `g_interactive` の名前がちょっと似てるので、もっと違う命名ができたらと思っています。
案：
- `g_interrupted`: `g_catched_signal`
- `g_interactive`: `g_shell_interactive`

2021-03-14 17:04 UTC, ToYeah requested changes
基本的な動作問題ないと思います！
`echo ^D hello`がちゃんと実行できました！

`SIGINT`と組み合わせたときの挙動が少し気になったので、コメントしてあります！

2021-03-14 17:04 UTC, ToYeah commented on srcs/main.c
> +		ft_safe_free_char(buf_line);
`hello ^D ^C ^D`という順番で入力すると、本家bashはexitするのですが、minishellはexitしないみたいです。
おそらく、`g_interrupted`によりfreeが行われたのち、`NULL`になった`buf_line`と`EOF`のみの`line`が`join`されて、`\0`のみの文字列が`buf_line`内に残るからだと思います。

2021-03-15 12:55 UTC, nafuka11 commented on srcs/main.c
> +		ft_safe_free_char(buf_line);
`g_interrupted` が TRUEの時（^Cが押された時）に ^D が押された場合、exitするよう修正しました！

以下のテストケースを確認しました。
^D->^C->^D と、^D->^\\->^D のケースを試しています。

No | 条件 | 入力 | 出力 | 終了ステータス
-- | -- | -- | -- | --
25 | aaaa<Ctrl+D><Ctrl+C><Ctrl+D> | <>の箇所入力 | bash-3.2$ aaaa<br>bash-3.2$ exit | 1
26 | aaaa<Ctrl+D><Ctrl+\\><Ctrl+D><Enter> | <>の箇所入力 | bash-3.2$ aaaa<br>bash: aaaa: command not found<br>bash-3.2$ | 127
27 | aaaa<Ctrl+D><Ctrl+C><Enter><Enter> | <>の箇所入力 | bash-3.2$ aaaa<br>bash-3.2$ <br>bash-3.2$ | 1
28 | aaaa<Ctrl+D><Ctrl+C>aaaa<Enter> | <>の箇所入力 | bash-3.2$ aaaa<br>bash-3.2$ aaaa<br>bash: aaaa: command not found | 127

2021-03-15 14:35 UTC, ToYeah approved these changes

2021-03-15 14:35 UTC, merged