[exec] pipeの実装
ToYeah/42_minishell pull request #33
Opened 2021-02-26 12:54 UTC by nafuka11

Fix #23

## やったこと
### parse処理、t_command構造体の変更
t_command構造体にnextを追加してlistにできるようにし、parse時にpipeで繋ぐ必要があるt_commandをnextで繋ぐようにしています。
`a | b | c ; d | e` を図にすると以下のような感じになります。
![2021-02-26 21-01-43](https://user-images.githubusercontent.com/42476527/109299779-fcf11a00-7878-11eb-8c3a-a36f00900705.png)
まだ、リダイレクトは実装していません。

### pipeの実装
exec_pipelineとexec_commandを変更しました。
nodeがpipeの場合、木を左に降りて、降りた先のコマンドからnextを辿って各コマンドを実行しつつ、pipeを使って標準入出力を繋ぎます。
![2021-02-26 21-27-03](https://user-images.githubusercontent.com/42476527/109300510-ef885f80-7879-11eb-9c65-60e73997f487.png)

実装の注意点として、各pipeは親・子プロセス全体で入り口・出口を1つずつにしないといけないです。

![IMG_20210226_2134502](https://user-images.githubusercontent.com/42476527/109301568-7e49ac00-787b-11eb-82c7-e6e3eafcaf49.png)

### 各関数について

関数 | 説明
-- | --
exec_list | exec_pipeline か exec_command を処理する関数です。Shellの文法に則ってlistという命名にしています。ただ分かりづらいかもしれません。
exec_pipeline | t_pipe_stateを PIPE_WRITE_ONLY(最初) -> PIPE_READ_WRITE(真ん中) -> PIPE_READ_ONLY(最後) に設定し、コマンドを実行します。
exec_command | コマンドを実行します。t_pipe_stateに応じてパイプを作成、dupします。
create_pipe | t_pipe_stateが書き込み可能なら新しいパイプを作成します。
dup_pipe | パイプをstdinかstdoutにdupしつつcloseします。
cleanup_pipe | 古いパイプがあるならcloseし、新しいパイプがあるなら古いパイプを更新します。
can_write | t_pipe_stateが書き込み可能なら TRUE、不可なら FALSE を返します。
can_read | t_pipe_stateが読み込み可能なら TRUE、不可なら FALSE を返します。

## テスト
以下のコマンドでテストを実行することができます。

```bash
cd tests
./grademe.sh
```
### テストケース
実装当時は、絶対パスでしかコマンドを実行できなかったので、絶対パス指定してあります。

単体コマンド
- /bin/ls

単体コマンド + 引数あり
- /bin/ls -a

2つのコマンドのパイプ
- /bin/ls | /usr/bin/grep a

3つのコマンドのパイプ
- /bin/ls | /usr/bin/grep a | /usr/bin/grep c

2021-02-26 14:45 UTC, ToYeah requested changes
処理の流れがすごくわかりやすかったです。

パイプを見つけると、パイプに関連する処理をすべて実行。
パイプを生成してから、一番左のプロセスをWRITE_ONLYで実行し、パイプの`fd[0]`をclose,`fd[1]`を先頭プロセスのSTDOUTにつなげる。
中間プロセスは前プロセスから引き継いだ`old_pipe`の`fd[0]`を`STDIN`につなげ、`new_pipe`の`fd[1]`に`STDOUT`をつなげる。
`pipe_cleanup`内で`new_pipe`を`old_pipe`に移動。
`command->next`が`NULL`であるプロセス、終端プロセスを見つけると、`READ_ONLY`で`exec`処理を実行。`old_pipe`の`fd[0]`を`STDIN`につなげ、pipeをcloseして`exec`終了
という流れで処理が行われると理解しました。

ゾンビプロセスが発生しているようなので、修正をお願いしたいです。

2021-02-26 14:45 UTC, ToYeah commented on srcs/exec/exec.c
> +	if (waitpid(pid, &status, 0) < 0)
exec_command内でforkしたプロセスのpid_tを捨ててしまっているため最後のプロセス以外がゾンビプロセスになっているようです。
[ゾンビプロセスをなかなか見ることができない理由](https://meetup-jp.toast.com/2162)を参考にゾンビプロセスを確認するコマンド `ps -e -o pid,stat,comm | grep Z+`を、パイプを含むコマンド実行後に実行したところ、ゾンビプロセスが生まれているようでした。
pidさえ覚えていればプロセス終了後でもwaitできたはず ( どこかで見ました。ソースなくてすみません... ) なので、exec_commandの返り値をリストで保持し、最後のプロセスを実行した後、リスト内のpidを順番にwaitpidしていくと解決できるのかな？と思っています。

![zombie](https://user-images.githubusercontent.com/62199197/109308484-6bd47000-7885-11eb-86bf-bf928975aaa7.png)

2021-02-26 14:45 UTC, ToYeah commented on srcs/exec/exec.c
> +	if (waitpid(pid, &status, 0) < 0)
`/bin/ls`を実行したときの挙動が少し不思議でした。
```
minishell > /bin/cat | /bin/ls
ast.dot  includes  libft  Makefile  minishell  srcs  tests
minishell > /bin/cat | /bin/ls

minishell > /bin/cat | /bin/ls
ast.dot  includes  libft  Makefile  minishell  srcs  tests
minishell > /bin/cat | /bin/ls

minishell > 
```


コマンドを入力するたびに`ls`の結果表示と`cat`の入力待ちが交互に発生しました。
`cat`は入力待ちが終了するたびに1つゾンビ化しているようです。(4回実行後`cat`のゾンビが2つだけ存在している状態)
本家の挙動は`ls`の実行結果表示後に`cat`の入力待ちが発生します。
`ls`の動作は入力に依存しないので`cat`の終了を待たずに処理が走り、結果表示。
`cat`は入力に依存するため入力待ちという認識です。(`ls`の動作が早いのかも？)

2021-02-26 14:45 UTC, ToYeah commented on includes/exec.h
> +# define PIPE_OUT					1
プロセス視点か、パイプ視点かの違いだと思うのですが、僕のイメージでは、プロセスがパイプの内容を読み取るfdが、パイプからプロセスへの出力側なので`PIPE_OUT`、プロセスからパイプへ出力する側fdがパイプがプロセスから入力を受け取る側なので`PIPE_IN`でした。

`STDIN`や`STDOUT`がプロセス視点なので、パイプもINがプロセス側から入力を受ける`fd[1]`,OUTがプロセスへ出力する`fd[0]`にしたほうがプロセスと同じ命名になるかなと思いました。

shellの文法的に左から右に処理が走るので、`fd[1]`を`PIPE_LEFT`、`fd[0]`を`PIPE_RIGHT`でもいいかもしれないです。

2021-02-26 15:58 UTC, nafuka11 commented on srcs/exec/exec.c
> +	if (waitpid(pid, &status, 0) < 0)
819efe4 にて、forkした全てのプロセスをwaitpidするよう修正しました！

t_command構造体にpidを追加し、`exec_command` で pid格納。
`wait_commands` でt_commandリストのpidを全て waitpidするようにしました。

2021-02-26 16:06 UTC, nafuka11 commented on includes/exec.h
> +# define PIPE_OUT					1
たしかに、`PIPE_IN`, `PIPE_OUT` だとプロセス視点なのかパイプ視点なのか分かりづらいですね。

pipe_stateを PIPE_READ_ONLY, PIPE_WRITE_ONLY, PIPE_READ_WRITE で分けてるので、
`fd[1]` = `PIPE_READ`
`fd[0]` = `PIPE_WRITE`
のように READ/WRITEで統一するといいかなと思いました。

`PIPE_LEFT` と `PIPE_RIGHT` も、分かりやすくていいですね。

2021-02-26 16:09 UTC, ToYeah commented on includes/exec.h
> +# define PIPE_OUT					1
`PIPE_LEFT`と`PIPE_RIGHT`にしましょう！

2021-02-26 16:29 UTC, ToYeah commented on srcs/exec/exec.c
> +	if (waitpid(pid, &status, 0) < 0)
`/bin/ls | /bin/grep make`、 `/bin/cat | /bin/ls`でbashと同じ挙動になっていることを確認しました！

僕の考えた処理の手順的に仕方ないのですが、`cat `の入力待ち中に`ls`がゾンビとして検出できるみたいです。
bashやほかのチームのシェルでは検出されないようなのでもっとうまい待ち方があるのかもしれません...!
調べてみます。

2021-02-27 07:09 UTC, nafuka11 commented on srcs/exec/exec.c
> +	if (waitpid(pid, &status, 0) < 0)
ゾンビプロセスは今回一旦対応しないことにします。
#37 で対応します。

2021-02-27 07:10 UTC, nafuka11 commented on includes/exec.h
> +# define PIPE_OUT					1
PIPR_IN, PIPE_OUT の値を入れ替えて対応することになりました。

2021-02-27 07:11 UTC, ToYeah approved these changes

2021-02-27 07:12 UTC, merged