exportコマンド実装
ToYeah/42_minishell pull request #84
Opened 2021-03-08 16:58 UTC by nafuka11

2021-03-10 03:15 UTC, nafuka11 commented
unset 、そんなにコード量多くないので、同じPRにまとめてしまおうと思います。

2021-03-10 03:30 UTC, nafuka11 commented
Fix #75

## unset実装

export と同じように引数をどんどん見て行って、 `is_identifier` が TRUE なら環境変数を削除（`del_env`）します。FALSE ならエラーメッセージを表示して、次の引数に進みます。

export と違い、引数を環境変数名として判定します。=や+=が含まれる場合NGとします。

### テストケース

ケース | 説明
-- | --
unset; env \| grep -v -E '^_=' \| sort | 正常系：unset単体
unset A; echo $A, export A='test $A' | 正常系：unset {存在する環境変数}
unset _A1; echo $_A1, export _A1='test $_A1' | 正常系：環境変数名に _アルファベット数字が入る時
unset A B C; echo $A$B$C$D, export A=test B=multiple C=var D=hello | 正常系：複数の環境変数を削除した時
unset A B =invalid C; echo $A$B$C$D, export A=test B=multiple C=var D=hello | 途中で不正な環境変数名が指定された場合
unset PWD; echo $PWD | 正常系：PWD
unset OLDPWD; echo $OLDPWD | 正常系：OLDPWD
unset NO_SUCH_ENV; echo $?$NO_SUCH_ENV, unset NO_SUCH_ENV | 正常系：存在しない環境変数名
unset 1 | 異常系：最初の文字が数字の環境変数名
unset A=a; echo $A, export A=a | 異常系：=を含む環境変数名
unset ' \"$&`\n' | 異常系：記号を含む環境変数名

2021-03-10 16:59 UTC, ToYeah requested changes
基本的な動作問題ないと思います！
マージソートがめちゃめちゃきれいで感動しました！！！！
公開されてるテストケース試してみたら緑ばかりでいよいよ終わりが近づいてきた感じがします...!

２つ気になるところがあったのでコメントつけました。
シェル変数の昇格は、`export 変数名`の時は`env`を探して見つけたら`is_env`を`TRUE`に、見つからなかったら`value`が`NULL`で新規作成みたいな処理がいいかなと思っています

2021-03-10 16:59 UTC, ToYeah commented on srcs/builtin/mini_export.c
> +	}
`minishell_debug`で`export = `を実行するとheap buffer overflowで落ちるみたいです。
`sep`を利用したif文に`ft_strlen`系の処理か`sep != arg`のようなs`ep-1`の読み込みを保証する処理を追加してほしいです！！

2021-03-10 16:59 UTC, ToYeah commented on srcs/builtin/mini_export.c
> +			update_env_value(args[i], value, TRUE, append_flag);
先頭が変数名として使用可能な名前の場合、separate_argもis_identifierも無条件にTRUEが出てしまうようです。そのため、`export PATH; export | grep PATH`のようなテストを実行すると、PATHがNULLになってしまい、KOになってしまいます。本家bashはPATH残ったままみたいです。

2021-03-10 16:59 UTC, ToYeah commented on srcs/builtin/mini_export.c
> +			update_env_value(args[i], value, TRUE, append_flag);
export 変数名のコマンドは、シェル変数を環境変数に昇格させることができるみたいです。
細かいところではあるんですがcd側でシェル変数を実装してしまっているので、以下の挙動も再現できるとカッコいいかなと思います！！
```
bash-3.2$ export | /usr/bin/grep PWD  
declare -x OLDPWD
declare -x PWD="/Users/totaisei/42_minishell"
bash-3.2$ unset PWD
bash-3.2$ export | /usr/bin/grep PWD
declare -x OLDPWD
bash-3.2$ cd ..
bash-3.2$ export | /usr/bin/grep PWD
declare -x OLDPWD=""
bash-3.2$ echo $PWD
/Users/totaisei
bash-3.2$ export PWD                
bash-3.2$ export | /usr/bin/grep PWD
declare -x OLDPWD=""
declare -x PWD="/Users/totaisei"
```

```
minishell > export | /usr/bin/grep PWD  
declare -x OLDPWD
declare -x PWD="/Users/totaisei/42_minishell"
minishell > unset PWD
minishell > export | /usr/bin/grep PWD
declare -x OLDPWD
minishell > cd ..
minishell > export | /usr/bin/grep PWD
declare -x OLDPWD=""
declare -x PWD="/Users/totaisei"
minishell > echo $PWD
/Users/totaisei
minishell > 
minishell > export PWD 
minishell > export | /usr/bin/grep PWD
declare -x OLDPWD=""
declare -x PWD
```

2021-03-11 02:05 UTC, nafuka11 commented on srcs/builtin/mini_export.c
> +	}
ありがとうございます！！
`*sep != arg` の処理を追加し、文字列の範囲を超えて `*sep - 1` を読みに行かないよう修正しました！
fa769bd

2021-03-11 04:54 UTC, nafuka11 commented on srcs/builtin/mini_export.c
> +			update_env_value(args[i], value, TRUE, append_flag);
> 先頭が変数名として使用可能な名前の場合、separate_argもis_identifierも無条件にTRUEが出てしまうようです。そのため、export PATH; export | grep PATHのようなテストを実行すると、PATHがNULLになってしまい、KOになってしまいます。本家bashはPATH残ったままみたいです。

PATHだけでなく、他の環境変数でも、既に存在する環境変数を `export {環境変数名}` すると、値が更新されないみたいです。
```bash
bash-3.2$ export A=test
bash-3.2$ export A
bash-3.2$ export | grep A
declare -x A="test"
```

a030edf で、環境変数更新の際、既にenvが存在し `new_value` がNULLの時値をsetしないよう修正しました！

修正した関数を既に使っていた箇所での影響は以下です。
- update_env_value("OLDPWD", get_env_data("PWD"), FALSE, FALSE);
  - 問題なし：`get_env_data` でNULLが入ることはない（PWDがNULLの場合""が返る）
- update_env_value("PWD", g_pwd, FALSE, FALSE);
  - 多分問題なし： `g_pwd` をセットする `get_new_pwd`, `pwd_value_init` どちらも NULL が返る場合 `error_exit` してそうです。

2021-03-11 05:04 UTC, nafuka11 commented on srcs/builtin/mini_export.c
> +			update_env_value(args[i], value, TRUE, append_flag);
> export 変数名のコマンドは、シェル変数を環境変数に昇格させることができるみたいです。
細かいところではあるんですがcd側でシェル変数を実装してしまっているので、以下の挙動も再現できるとカッコいいかなと思います！！

export 変数名のコマンド では `is_env` を強制 TRUE にして、環境変数に昇格していたつもりでした（3番目の引数が `is_env` の指定です）。

https://github.com/ToYeah/42_minishell/blob/72f41d2386c72d6aa76016610d373006f489824f/srcs/builtin/mini_export.c#L77

しかし、export 単体の表示で、 `is_env` が FALSE なら表示しない処理を実装しておらず、全てのenvを出力してしまっていました。

https://github.com/ToYeah/42_minishell/blob/95dfd9c930029b33f1a0cba7af7c21a615e3b652/srcs/builtin/mini_export_print.c#L16-L31

b104edb で表示処理の修正を行いました！

2021-03-11 09:15 UTC, ToYeah commented on srcs/builtin/mini_export.c
> +			update_env_value(args[i], value, TRUE, append_flag);
`env`の修正ありがとうございます！！
https://github.com/ToYeah/42_minishell/blob/72f41d2386c72d6aa76016610d373006f489824f/srcs/utils/env_utils.c#L89
`update_env_value`内で`is_env`が更新されるのはenvが見つからず新規作成したときだけなので昇格処理が効いてないみたいです！

2021-03-11 11:21 UTC, nafuka11 commented on srcs/builtin/mini_export.c
> +			update_env_value(args[i], value, TRUE, append_flag);
失礼しました！修正できていませんでした……！
既存envが存在するときも昇格するよう修正しました！（ d9eb081 ）
テストも追加しています！（ 0900c81 ）

2021-03-11 12:02 UTC, ToYeah approved these changes
修正確認しました！問題ないと思います！

2021-03-11 12:02 UTC, merged